In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)


2.6.0+cu126


In [4]:
#scalar
scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [5]:
scalar.ndim

0

In [ ]:
# get tensor scalar as int as int
scalar.item()

7

In [ ]:
#Vector
vector = torch.tensor([7,7])
print(vector)

tensor([7, 7])

In [9]:
vector.shape

torch.Size([2])

In [10]:
vector.ndim

1

In [12]:
# Matrix
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [13]:
MATRIX.ndim

2

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [15]:
MATRIX[0]

tensor([7, 8])

In [16]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
#Tensor 

TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [19]:
TENSOR.ndim

3

In [20]:
TENSOR.shape

torch.Size([1, 3, 3])

In [21]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [25]:
TENSOR[0,0,0]

tensor(1)

In [17]:
#Dobra własna zabawa

t1 = torch.tensor([[[1,2,3],
                    [4,5,6],
                    [7,8,9]],
                    [[3,3,3],
                     [3,3,3],
                     [3,3,3]],
                     [[0,0,0],
                      [1,1,1],
                      [1,3,5]]])
t1

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[3, 3, 3],
         [3, 3, 3],
         [3, 3, 3]],

        [[0, 0, 0],
         [1, 1, 1],
         [1, 3, 5]]])

In [29]:
t1.ndim

3

In [30]:
t1.shape

torch.Size([3, 3, 3])

In [39]:
t1[0,:,0]

tensor([1, 4, 7])

In [44]:
t1[0,:,:]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [50]:
# Random tensors

random_tensor = torch.rand(1,3,4)
print(random_tensor)
random_tensor.ndim

tensor([[[0.4165, 0.2878, 0.0654, 0.1194],
         [0.0141, 0.1633, 0.8199, 0.2999],
         [0.5224, 0.1621, 0.5002, 0.0857]]])


3

In [51]:
#create a random tensor with shape like image

random_image_size_tensor = torch.rand(size=(3,224,224))# chanels, width,height 


In [3]:
zero = torch.zeros(3,4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [4]:
one = torch.ones(3,4)
one

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [5]:
one.dtype

torch.float32

In [6]:
oneToTen = torch.arange(start=1, end= 11, step=1)
oneToTen 

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
ten_zeroes = torch.zeros_like(input=oneToTen)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
float_32_tensor = torch.tensor([3.5, 6.232, 9.1],dtype=None, device=None,requires_grad=False)

float_32_tensor

tensor([3.5000, 6.2320, 9.1000])

In [6]:
float_32_tensor.dtype

torch.float16

In [8]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [11]:
mnoz = float_16_tensor * float_32_tensor
mnoz.dtype

torch.float32

In [12]:
uint = torch.tensor([3,2,1],dtype=torch.uint8)
integer = torch.tensor([-3,2,-4], dtype=torch.int8)
dziwneMnozenie = uint * integer
print(dziwneMnozenie)

tensor([-9,  4, -4], dtype=torch.int16)


In [15]:
int_32_tensor = torch.tensor([3,5,9],dtype=torch.int32)
mno = int_32_tensor*float_32_tensor
mno.dtype

torch.float32

In [31]:

tension = torch.rand(3,4)
tension

tensor([[0.1292, 0.0737, 0.1682, 0.9131],
        [0.5993, 0.5442, 0.1482, 0.2216],
        [0.9656, 0.7144, 0.3378, 0.1511]])

In [32]:
print(tension)
print(f"Datatype: {tension.dtype}")
print(f"Shape: {tension.shape}")
print(f"Device: {tension.device}")

tensor([[0.1292, 0.0737, 0.1682, 0.9131],
        [0.5993, 0.5442, 0.1482, 0.2216],
        [0.9656, 0.7144, 0.3378, 0.1511]])
Datatype: torch.float32
Shape: torch.Size([3, 4])
Device: cpu


In [7]:
#Operacje matematyczne
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [4]:
tensor * 10

tensor([10, 20, 30])

In [5]:
tensor - 10

tensor([-9, -8, -7])

In [ ]:


print(tensor, "*", tensor)
print(f"Equlas: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equlas: tensor([1, 4, 9])


In [10]:
# Macierzowe mnożenie 
torch.matmul(tensor, tensor)

tensor(14)

In [21]:
t1 = torch.tensor([[1],[2],[3],[4]]) 
t1

tensor([[1],
        [2],
        [3],
        [4]])

In [22]:
t2 = torch.tensor([[5,6,7,8]])
t2

tensor([[5, 6, 7, 8]])

In [18]:
torch.matmul(t1,t2)

tensor([[ 5,  6,  7,  8],
        [10, 12, 14, 16],
        [15, 18, 21, 24],
        [20, 24, 28, 32]])

In [31]:
A = torch.tensor([[1,2],[3,4],[5,6]])

B = torch.tensor([[7,10],[8,11],[9,12]])
torch.matmul(A,B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [34]:
B = B.T

In [35]:
torch.mm(A,B)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [36]:
torch.mm(B,A)

tensor([[ 76, 100],
        [103, 136]])

In [46]:
#Finding min, max, mean, sum, etc

x = torch.arange(0,100, 10)
x 

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [39]:
x.min()

tensor(0)

In [40]:
x.max()

tensor(90)

In [47]:
x.mean()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [48]:
x.type(torch.float32).mean()

tensor(45.)

In [50]:
x.sum()
torch.sum(x)

tensor(450)

In [ ]:
#Dodatkowo zwracany indeks
torch.min(x,0)
torch.max(x,0)
x.min(0)

torch.return_types.max(
values=tensor(90),
indices=tensor(9))

In [55]:
x.median(0)

torch.return_types.median(
values=tensor(40),
indices=tensor(4))