In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)


2.6.0+cu126


In [4]:
#scalar
scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [5]:
scalar.ndim

0

In [ ]:
# get tensor scalar as int as int
scalar.item()

7

In [ ]:
#Vector
vector = torch.tensor([7,7])
print(vector)

tensor([7, 7])

In [9]:
vector.shape

torch.Size([2])

In [10]:
vector.ndim

1

In [12]:
# Matrix
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [13]:
MATRIX.ndim

2

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [15]:
MATRIX[0]

tensor([7, 8])

In [16]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
#Tensor 

TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [19]:
TENSOR.ndim

3

In [20]:
TENSOR.shape

torch.Size([1, 3, 3])

In [21]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [25]:
TENSOR[0,0,0]

tensor(1)

In [ ]:
#Dobra własna zabawa

t1 = torch.tensor([[[1,2,3],
                    [4,5,6],
                    [7,8,9]],
                    [[3,3,3],
                     [3,3,3],
                     [3,3,3]],
                     [[0,0,0],
                      [1,1,1],
                      [1,3,5]]])

In [29]:
t1.ndim

3

In [30]:
t1.shape

torch.Size([3, 3, 3])

In [39]:
t1[0,:,0]

tensor([1, 4, 7])